### ISSUE TITLE
Issue with statuses

### ISSUE THREAD

**Issue by tokr-coder** [MrEbabi/New-Order-Notification-for-Woocommerce-Plugin#2]
hi,
If I understand correctly, the setting "Notification Order Statuses" should let me choose which product statuses appear in the list of recent orders. Orders with a status that is not selected should not appear in the list. And if a new order appears in the list, a sound is played.
However, it doesn't seem to be working. I've selected "Pending", "Processing", and "On Hold"; but in the list I see everything from "Failed" to "Completed".
Am I misunderstanding how this is supposed to work?

**Comment by MrEbabi** [comment]
Hi, 

"Alert only for orders containing products with ID:" and "Notification Order Statuses:" options restrict only the alerts. The recent orders will listed without considering these options.

**Comment by MrEbabi** [comment]
I found your approach better. I am now changing the recent order table to show only the orders with selected statuses. Thanks for warning and contributing.
